# Generated by Django 5.1 on 2024-08-26 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('sent_date', models.DateTimeField()),
                ('received_date', models.DateTimeField()),
                ('body', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MailClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('service', models.CharField(choices=[('yandex', 'Yandex'), ('gmail', 'Gmail'), ('mailru', 'Mail.ru')], max_length=10)),
                ('imap_server', models.CharField(max_length=255)),
                ('imap_port', models.IntegerField(default=993)),
            ],
        ),
        migrations.CreateModel(
            name='EmailAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='attachments/')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='mail.emailmessage')),
            ],
        ),
        migrations.AddField(
            model_name='emailmessage',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mail.mailclient'),
        ),
    ]
